# dotfiles-chzemoi — convenience recipes. Run `just` or `just --list` to see all.
DOTFILES := justfile_directory()
BIN := DOTFILES / "bin/dotfiles"

default: help

# Show this help
help:
	@just --list --unsorted

# Run the full installer (aqua tools, plugins, chezmoi apply, fonts)
install:
	bash "{{ DOTFILES }}/install.sh"

# Back up + reset state (chezmoi destroy, clear local); prompts first
reset:
	bash "{{ DOTFILES }}/install/cleanup.sh"

# Like reset, but ALSO wipes var/ (tools, vendor, caches) + .zwc
hardreset:
	bash "{{ DOTFILES }}/install/cleanup.sh" --hard

# Apply home/ tree to $HOME via chezmoi
apply:
	"{{ BIN }}" apply

# Byte-compile the zsh framework (.zwc)
compile:
	"{{ BIN }}" compile

# Lint all scripts (shellcheck/zshellcheck/actionlint/editorconfig)
check:
	"{{ BIN }}" check

# Scan the working tree for secrets (betterleaks)
audit:
	"{{ BIN }}" audit

# Format shell scripts with shfmt (if installed)
fmt:
	#!/usr/bin/env bash
	set -euo pipefail
	if command -v shfmt >/dev/null 2>&1; then
	  shfmt -w -i 2 -ci "{{ DOTFILES }}/install" "{{ DOTFILES }}/bin" "{{ DOTFILES }}/config/shell"
	else
	  echo "shfmt not installed — skipping"
	fi

# Run the bats smoke tests
test:
	"{{ BIN }}" test

# Benchmark interactive zsh startup
bench:
	"{{ BIN }}" bench

# Health checks
doctor:
	"{{ BIN }}" doctor

# Mark all shebang scripts +x in git and on disk
fix-exec:
	bash "{{ DOTFILES }}/install/bin/fix-executable-bits.sh"

# Regenerate man/dotfiles.1 from the CLI help
man:
	"{{ BIN }}" doc man

# Remove generated bytecode (.zwc)
clean:
	find "{{ DOTFILES }}/config" -name '*.zwc' -delete
	@echo "removed .zwc"
