# dotfiles_v2 — convenience targets. Most wrap the `dotfiles` CLI.
DOTFILES := $(CURDIR)
BIN      := $(DOTFILES)/bin/dotfiles

.DEFAULT_GOAL := help

.PHONY: help install stow compile check audit fmt test bench doctor man clean reset hardreset

help: ## Show this help
	@awk 'BEGIN{FS=":.*##"} /^[a-zA-Z_-]+:.*##/{printf "  \033[1;32m%-10s\033[0m %s\n",$$1,$$2}' $(MAKEFILE_LIST)

install: ## Run the full installer (tools, plugins, stow, fonts)
	@bash $(DOTFILES)/install.sh

reset: ## Back up + reset state (unstow, clear caches/history/local); prompts first
	@bash $(DOTFILES)/install/cleanup.sh

hardreset: ## Like reset, but ALSO backs up + wipes var/ (tools, vendor, caches) + .zwc
	@bash $(DOTFILES)/install/cleanup.sh --hard

stow: ## (Re)create the dotfiles symlinks
	@$(BIN) stow

compile: ## Byte-compile the zsh framework (.zwc)
	@$(BIN) compile

check: ## Lint all scripts (shellcheck/zshellcheck/actionlint/editorconfig)
	@$(BIN) check

audit: ## Scan the working tree for secrets (betterleaks)
	@$(BIN) audit

fmt: ## Format shell scripts with shfmt (if installed)
	@command -v shfmt >/dev/null 2>&1 \
		&& shfmt -w -i 2 -ci $(DOTFILES)/install $(DOTFILES)/bin $(DOTFILES)/config/shell \
		|| echo "shfmt not installed — skipping"

test: ## Run the bats smoke tests
	@$(BIN) test

bench: ## Benchmark interactive zsh startup
	@$(BIN) bench

doctor: ## Health checks
	@$(BIN) doctor

man: ## Regenerate man/dotfiles.1 from the CLI help
	@$(BIN) doc man

clean: ## Remove generated bytecode (.zwc)
	@find $(DOTFILES)/config -name '*.zwc' -delete && echo "removed .zwc"
