#!/usr/bin/env bash
# Download Zellij WASM plugins into var/vendor/zellij-plugins/ and symlink
# them into the stowed config tree (config/stow/zellij/.config/zellij/plugins/).
set -euo pipefail
source "$(dirname "$0")/../common.sh"

FORCE=0
[ "${1:-}" = --force ] && FORCE=1

VENDOR="$DOTFILES/var/vendor/zellij-plugins"
STOW_PLUGINS="$STOW_DIR/zellij/.config/zellij/plugins"
mkdir -p "$VENDOR" "$STOW_PLUGINS"

fetch_wasm() {
  local label=$1 repo=$2 asset=$3
  local tag ver url dest link
  tag="$(gh_latest_tag "$repo")"
  [ -n "$tag" ] || { warn "$label: cannot resolve latest release of $repo"; return 1; }
  ver="${tag#v}"
  url="https://github.com/$repo/releases/download/$tag/$asset"
  dest="$VENDOR/$asset"
  link="$STOW_PLUGINS/$asset"

  if [ -f "$dest" ] && [ "$FORCE" -eq 0 ]; then
    skip "$label $tag (use --force to refresh)"
  else
    log "Fetching $label $tag"
    curl -fsSL --retry 3 --connect-timeout 20 -o "$dest" "$url"
    ok "$label -> $dest"
  fi
  ln -sfn "$dest" "$link"
}

have zellij || warn "zellij not on PATH yet — downloading plugins anyway"

fetch_wasm zsm      liam-mackie/zsm zsm.wasm
fetch_wasm zjstatus dj95/zjstatus   zjstatus.wasm
fetch_wasm zjframes dj95/zjstatus   zjframes.wasm
fetch_wasm monocle  imsnif/monocle  monocle.wasm

# Record pinned versions for debugging / doctor.
{
  printf '# generated by install-zellij-plugins.sh — do not edit\n'
  for f in "$VENDOR"/*.wasm; do
    [ -f "$f" ] || continue
    printf '%s\t%s\n' "$(basename "$f")" "$(readlink -f "$f")"
  done
} >"$VENDOR/.manifest" 2>/dev/null || true

ok "zellij plugins -> $VENDOR (symlinked into stow package)"
