"""Generate bugwarriorrc from local/tools/config.toml."""

import os
from typing import Any, Dict, List

from dotfiles_tools.config import (
    bugwarrior_output_path,
    bugwarrior_settings,
    gitlab_connection,
    jira_connection,
    load_config,
    password_oracle,
)


class RenderError(Exception):
    pass


def _ini_bool(value):
    # type: (Any) -> str
    return 'true' if value else 'false'


def _lines_for_jira(section_name, jira_cfg, bw_jira):
    # type: (str, Dict[str, Any], Dict[str, Any]) -> List[str]
    url = jira_cfg.get('url')
    email = jira_cfg.get('email') or jira_cfg.get('username')
    if not url:
        raise RenderError('jira.url required in config or JIRA_URL env')
    if not email:
        raise RenderError('jira.email required in config or JIRA_EMAIL env')

    lines = [
        '[{}]'.format(section_name),
        'service = jira',
        'jira.base_uri = {}'.format(url.rstrip('/')),
        'jira.username = {}'.format(email),
        'jira.password = {}'.format(password_oracle('JIRA_API_TOKEN')),
    ]
    query = bw_jira.get('query')
    if query:
        lines.append('jira.query = {}'.format(query))
    if bw_jira.get('import_labels_as_tags') is not None:
        lines.append('jira.import_labels_as_tags = {}'.format(
            _ini_bool(bw_jira.get('import_labels_as_tags'))))
    if bw_jira.get('import_sprints_as_tags') is not None:
        lines.append('jira.import_sprints_as_tags = {}'.format(
            _ini_bool(bw_jira.get('import_sprints_as_tags'))))
    if jira_cfg.get('verify_ssl') is False:
        lines.append('jira.verify_ssl = false')
    return lines


def _lines_for_gitlab(section_name, gl_cfg, bw_gl):
    # type: (str, Dict[str, Any], Dict[str, Any]) -> List[str]
    url = gl_cfg.get('url')
    if not url:
        raise RenderError('gitlab.url required in config or GITLAB_URL env')

    lines = [
        '[{}]'.format(section_name),
        'service = gitlab',
        'gitlab.baseuri = {}'.format(url.rstrip('/')),
        'gitlab.token = {}'.format(password_oracle('GITLAB_TOKEN')),
    ]
    repos = bw_gl.get('include_repos') or bw_gl.get('repos')
    if repos:
        lines.append('gitlab.include_repos = {}'.format(','.join(repos)))
    assignee = bw_gl.get('filter_assignee') or bw_gl.get('assignee')
    if assignee:
        lines.append('gitlab.filter_assignee = {}'.format(assignee))
    if gl_cfg.get('verify_ssl') is False:
        lines.append('gitlab.ssl_verify = false')
    return lines


def render_bugwarriorrc():
    # type: () -> str
    config = load_config()
    bw = bugwarrior_settings()
    targets = bw.get('targets') or ['jira']
    if isinstance(targets, str):
        targets = [targets]

    jira_cfg = jira_connection()
    gl_cfg = gitlab_connection()
    bw_root = config.get('bugwarrior') or {}
    bw_jira = bw_root.get('jira') or {}
    bw_gl = bw_root.get('gitlab') or {}

    lines = [
        '# Generated by: dotfiles bugwarrior render',
        '# Source: local/tools/config.toml',
        '# Tokens: dotfiles secrets (keyring) -> env at runtime',
        '',
        '[general]',
        'targets = {}'.format(','.join(targets)),
        'maintenance = {}'.format(_ini_bool(bw.get('maintenance', False))),
        '',
    ]

    for target in targets:
        name = str(target).strip()
        if name == 'jira':
            lines.extend(_lines_for_jira(name, jira_cfg, bw_jira))
            lines.append('')
        elif name == 'gitlab':
            lines.extend(_lines_for_gitlab(name, gl_cfg, bw_gl))
            lines.append('')
        else:
            raise RenderError('unsupported bugwarrior target: {}'.format(name))

    return '\n'.join(lines).rstrip() + '\n'


def write_bugwarriorrc(path=None, dry_run=False):
    # type: (str, bool) -> str
    out_path = path or bugwarrior_output_path()
    content = render_bugwarriorrc()
    if dry_run:
        return content
    parent = os.path.dirname(out_path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(out_path, 'w', encoding='utf-8') as handle:
        handle.write(content)
    return out_path
