#!/bin/sh
# TigerVNC session startup (no self-kill on gnome exit).
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
export XDG_RUNTIME_DIR=/tmp/runtime-vnc$$
mkdir -p "$XDG_RUNTIME_DIR"
chmod 700 "$XDG_RUNTIME_DIR"
[ -x /etc/X11/xinit/xinitrc ] && exec /etc/X11/xinit/xinitrc
